# Generated by Django 4.0.3 on 2022-03-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
