# Generated by Django 4.0.3 on 2022-03-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='created_at',
        ),
    ]
