# Generated by Django 4.0.3 on 2022-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_date_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='book', to='books.category'),
        ),
    ]
